# Generated by Django 5.1 on 2024-10-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symptom", models.CharField(max_length=255)),
                ("diagnosis", models.TextField()),
                ("treatment", models.TextField()),
                ("medication", models.TextField()),
            ],
        ),
    ]
